Suplier
CheckoutPro/CheckoutProBack pull request #5
Opened 2024-06-19 01:28 UTC by RaulKlahold

subindo minha Entity

2024-06-19 02:35 UTC, chenriquedev requested changes
Change the generate value

2024-06-19 02:49 UTC, RaulKlahold commented
Atualizai o UUID na geração de ids dos fornecedores

2024-06-20 02:56 UTC, chenriquedev submitted a review, later dismissed
ok

2024-06-21 01:30 UTC, RaulKlahold commented
criação do Suplier repository

2024-06-21 01:37 UTC, chenriquedev approved these changes
ok

2024-06-21 01:47 UTC, closed without merging